# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Parse Open Source Hub
title: Parse + Open Source = ❤️
email: community@parse.com
description: The open source GitHub page for the Parse platform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://parseplatform.github.io/" # the base hostname & protocol for your site
facebook_username: parseit
twitter_username:  parseit
github_username:   parseplatform
stackoverflow_tag: parse.com
serverfault_tag:   parse
support_url: https://www.parse.com/help

# Build settings
markdown: kramdown
exclude: [ README.md, config.codekit ]
